# Result #1
SELECT P_DESCRIPT, P_QOH, P_PRICE, V_CODE
FROM PRODUCT
WHERE V_CODE = 21344 OR V_CODE = 24288;

# Result #2
SELECT P_DESCRIPT, P_QOH, P_PRICE, V_CODE
FROM PRODUCT
WHERE (V_CODE = 25595 OR V_CODE = 24288) AND P_PRICE > 100;

# Result #3
SELECT *
FROM PRODUCT
WHERE NOT (V_CODE = 21344);

# Result #4
SELECT *
FROM PRODUCT
WHERE P_PRICE BETWEEN 50 AND 100; # Gets all the data where the price is between $50 to $100

# Result #5
SELECT *
FROM PRODUCT 
WHERE V_CODE IN (21344, 24288, 25595); # Gets all values if V_CODE IS 21344, or 24288, or 25595

# Result #6
SELECT V_NAME, V_CONTACT, V_AREACODE
FROM VENDOR
WHERE V_CONTACT LIKE 'Smith%'; # 

# Result #7
SELECT *
FROM VENDOR
WHERE V_CONTACT LIKE 'JOHNS_N';

# Result #8
SELECT P_CODE, P_DESCRIPT, V_CODE
FROM PRODUCT
WHERE V_CODE IS NULL;

# Result #9
SELECT P_CODE, P_DESCRIPT, V_CODE, V_NAME, V_AREACODE, V_PHONE
FROM PRODUCT NATURAL JOIN VENDOR; # NATURAL JOIN joins 2 tables based on common attributes

# Result #10
SELECT CUS_CODE, CUS_LNAME, INV_NUMBER, INV_DATE 
FROM CUSTOMER NATURAL JOIN INVOICE; # Joines CUSTOMER and INVOICE

# Result #11
SELECT INV_NUMBER, P_CODE, P_DESCRIPT, LINE_UNITS, LINE_PRICE
FROM INVOICE NATURAL JOIN LINE NATURAL JOIN PRODUCT; # Joines 3 tables: INVOICE, LINE, and PRODUCT

# Result #12
SELECT P_CODE, P_DESCRIPT, V_CODE, V_NAME, V_AREACODE, V_PHONE
FROM PRODUCT JOIN VENDOR USING (V_CODE); # USING Returns rows from PRODUCT and VENDOR when the values in V_CODE 

# Result #13
SELECT P_CODE, VENDOR.V_CODE, V_NAME
FROM PRODUCT JOIN VENDOR ON VENDOR.V_CODE = PRODUCT.V_CODE;

# Result #14
SELECT P_CODE, V_CODE, V_NAME
FROM PRODUCT JOIN VENDOR USING (V_CODE);

# Result #15
SELECT INVOICE.INV_NUMBER, PRODUCT.P_CODE, P_DESCRIPT, LINE_UNITS, LINE_PRICE # Identify INVOICE & PRODUCT from which table
FROM INVOICE JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER # Joins INVOICE & LINE based on INV_NUMBER (for INVOICE & LINE)
JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE; # Joins LINE & PRODUCT based on P_CODE




